services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./cloud_platform/data/mosquitto/config:/mosquitto/config
      - ./cloud_platform/data/mosquitto/data:/mosquitto/data
      - ./cloud_platform/data/mosquitto/log:/mosquitto/log
      - ./cloud_platform/data/mosquitto/config/certs:/mosquitto/certs
    networks:
      - idc-net
  app:
    build: ./cloud_platform/app
    container_name: app
    depends_on: 
      - mosquitto
      - db
    networks:
      - idc-net
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cloud_platform/data/db:/docker-entrypoint-initdb.d
    networks:
      - idc-net
  ml_processor:
    build: ./cloud_platform/ml_processor
    container_name: ml_processor
    volumes:
      - ./cloud_platform/ml_processor/models:/ml_processor/models
    ports:
      - 5000:5000
    depends_on:
      - db
      - app
    networks:
      - idc-net  


volumes:
  postgres_data:

networks:
  idc-net:
      driver: bridge

