services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./cloud_platform/data/mosquitto/config:/mosquitto/config
      - ./cloud_platform/data/mosquitto/data:/mosquitto/data
      - ./cloud_platform/data/mosquitto/log:/mosquitto/log
      - ./cloud_platform/data/mosquitto/config/certs:/mosquitto/certs
    networks:
      - idc-net
  app:
    build: ./cloud_platform/app
    container_name: app
    depends_on: 
      - mosquitto
    networks:
      - idc-net



networks:
  idc-net:
      driver: bridge

